### ISSUE TITLE
Rename plugin name to Customizer Reset by WPZOOM

### ISSUE THREAD

**Issue by claytoncollie** [wpzoom/customizer-reset#5]
Keep plugin slug the same but change the name. I do not think this is a breaking change.

**Comment by ciorici** [comment]
I'm afraid that this might suggest to users that the plugin works only with WPZOOM themes.

**Comment by claytoncollie** [comment]
Probably fine if we use the readme to add more WPZOOM keywords instead of the Plugin Name.
